modLoader = "javafml"
loaderVersion = "[4,)"
license = "MIT"

[[mods]]
modId = "cobbleride"
version = "${version}"
displayName = "Cobblemon: Ride On!"
description = '''
Ride astride your Pokemon companions, as you travel by land, air or sea together!
'''

[[mixins]]
config = "cobbleride.mixins.json"

[[dependencies.cobbleride]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1]"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobbleride]]
modId = "neoforge"
mandatory = true
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobbleride]]
modId = "cobblemon"
mandatory = true
versionRange = "[1.6.0,)"
ordering = "NONE"
side = "BOTH"
